version: '3.3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  redis:
    image: redis

  app:
    build:
      context: ./
    ports:
      - 5000:5000
    links:
      - db
      - redis
    volumes:
      - ./src:/go/src/app:cached
    command: "go run harekazectf.go"
